# Generated by Django 5.2.3 on 2025-07-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_costcenter_budgetitem_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='details',
            field=models.JSONField(default=dict, verbose_name='تفاصيل الموازنة'),
        ),
    ]
