# Generated by Django 5.2.3 on 2025-07-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budget_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='details',
        ),
    ]
