# Generated by Django 5.2.3 on 2025-07-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_journalentryline_cost_center'),
        ('budget', '0004_remove_budget_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('feb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('apr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('may', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jun', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aug', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sep', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('oct', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nov', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dec', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='budget.budget')),
            ],
            options={
                'verbose_name': 'بند موازنة سنوي',
                'verbose_name_plural': 'بنود الموازنة السنوية',
                'unique_together': {('budget', 'account')},
            },
        ),
    ]
