# Generated by Django 5.2.3 on 2025-07-15 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_budgetentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetentry',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budget'),
        ),
    ]
