# Generated by Django 5.2.3 on 2025-07-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_budgetentry_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetentry',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgetentry_set', to='budget.budget'),
        ),
    ]
