# Generated by Django 5.2.3 on 2025-07-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_budgetitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetItem',
        ),
    ]
