# Generated by Django 5.2.1 on 2025-07-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_budgetreportsfakemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetreportsfakemodel',
            options={'managed': False, 'verbose_name': '💵 تقارير الموازنة التقديرية', 'verbose_name_plural': '💵 تقارير الموازنة التقديرية'},
        ),
    ]
