# Generated by Django 5.2.3 on 2025-07-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الشركة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo/', verbose_name='شعار الشركة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('footer_note', models.TextField(blank=True, verbose_name='ملاحظة في التذييل')),
            ],
            options={
                'verbose_name': 'بيانات الشركة',
                'verbose_name_plural': 'بيانات الشركة',
            },
        ),
    ]
