# Generated by Django 5.2.3 on 2025-07-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchasesByProductAndSupplierFakeModel',
        ),
        migrations.DeleteModel(
            name='PurchasesBySupplierReportFakeModel',
        ),
        migrations.DeleteModel(
            name='SupplierLedgerReportFakeModel',
        ),
        migrations.AlterModelOptions(
            name='purchasereportsfakemodel',
            options={'managed': False, 'verbose_name': '🧾 تقارير المشتريات', 'verbose_name_plural': '🧾 تقارير المشتريات'},
        ),
    ]
