# Generated by Django 5.2.3 on 2025-07-31 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_delete_purchasesbyproductandsupplierfakemodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'verbose_name': 'فاتورة مشتريات', 'verbose_name_plural': 'فواتير المشتريات'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturn',
            options={'verbose_name': 'مردودات مشتريات', 'verbose_name_plural': 'مردودات المشتريات'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'مورد', 'verbose_name_plural': 'الموردون'},
        ),
        migrations.AlterModelOptions(
            name='suppliergroup',
            options={'verbose_name': 'مجموعة موردين', 'verbose_name_plural': 'مجموعات الموردين'},
        ),
        migrations.AlterModelOptions(
            name='supplierpayment',
            options={'verbose_name': 'دفعة مورد', 'verbose_name_plural': 'دفعات الموردين'},
        ),
    ]
