# Generated by Django 5.2.3 on 2025-08-01 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_purchaseinvoice_options_and_more'),
        ('sales', '0004_salesrepresentative_alter_salesinvoice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'verbose_name': 'فاتورة المشتريات', 'verbose_name_plural': 'فاتورة المشتريات'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturn',
            options={'verbose_name': 'فاتورة مردودات مشتريات', 'verbose_name_plural': 'فاتورة مردودات المشتريات'},
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesrepresentative'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesrepresentative'),
        ),
    ]
