# Generated by Django 5.2.3 on 2025-07-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='available_leave_balance',
            field=models.FloatField(default=0, verbose_name='رصيد الإجازات المتاحة'),
        ),
    ]
