# Generated by Django 5.2.3 on 2025-07-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_available_leave_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='available_leave_balance',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='is_approved',
        ),
    ]
