# Generated by Django 5.2.3 on 2025-07-23 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_employee_available_leave_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='opening_advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رصيد أولي للسلف'),
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ السلفة')),
                ('start_month', models.PositiveIntegerField(verbose_name='شهر البداية')),
                ('start_year', models.PositiveIntegerField(verbose_name='سنة البداية')),
                ('months_count', models.PositiveIntegerField(verbose_name='عدد الأشهر للخصم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='الموظف')),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='hr.advance')),
            ],
        ),
    ]
