# Generated by Django 5.2.3 on 2025-07-23 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_journalentry_description'),
        ('hr', '0004_employee_opening_advance_balance_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_cash_account', to='accounts.account', verbose_name='حساب الصرف'),
        ),
        migrations.AddField(
            model_name='advance',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry'),
        ),
        migrations.AddField(
            model_name='advance',
            name='loan_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_loan_account', to='accounts.account', verbose_name='حساب السلف'),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='advance_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم السلفة'),
        ),
    ]
