# Generated by Django 5.2.3 on 2025-07-23 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_journalentry_description'),
        ('hr', '0005_advance_cash_account_advance_journal_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='cash_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='advance_cash', to='accounts.account', verbose_name='حساب الصرف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advance',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='قيد السلفة'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='loan_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='advance_loans', to='accounts.account', verbose_name='حساب السلف'),
            preserve_default=False,
        ),
    ]
