# Generated by Django 5.2.3 on 2025-07-25 07:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_journalentry_description'),
        ('hr', '0006_alter_advance_cash_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRReportsFakeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '📊 تقارير الموارد البشرية',
                'verbose_name_plural': '📊 تقارير الموارد البشرية',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EndOfServiceReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الاستحقاق')),
                ('reason', models.CharField(choices=[('resignation', 'استقالة'), ('termination', 'إنهاء من قبل الشركة'), ('retirement', 'تقاعد'), ('other', 'أخرى')], max_length=20, verbose_name='سبب انتهاء الخدمة')),
                ('years_of_service', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='عدد سنوات الخدمة')),
                ('last_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='آخر راتب')),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مكافأة نهاية الخدمة')),
                ('is_posted', models.BooleanField(default=False, verbose_name='تم الترحيل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='الموظف')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الصرف')),
                ('days_entitled', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='عدد الأيام المستحقة')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر اليوم')),
                ('ticket_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل تذاكر السفر')),
                ('other_benefits', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مزايا أخرى')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المستحق')),
                ('is_posted', models.BooleanField(default=False, verbose_name='تم الترحيل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='الموظف')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='قيد اليومية')),
            ],
        ),
    ]
