# Generated by Django 5.2.3 on 2025-07-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_remove_leaveallowance_other_benefits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveallowance',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='leaveallowance',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='leaveallowance',
            name='notes',
        ),
        migrations.AddField(
            model_name='leaveallowance',
            name='base_salary_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='leaveallowance',
            name='extra_benefits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مزايا إضافية'),
        ),
        migrations.AddField(
            model_name='leaveallowance',
            name='housing_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='leaveallowance',
            name='other_allowances_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='leaveallowance',
            name='transport_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='leaveallowance',
            name='days_entitled',
            field=models.PositiveIntegerField(default=0, verbose_name='الأيام المستحقة'),
        ),
        migrations.AlterField(
            model_name='leaveallowance',
            name='pay_date',
            field=models.DateField(verbose_name='تاريخ الصرف'),
        ),
        migrations.AlterField(
            model_name='leaveallowance',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
