# Generated by Django 5.2.3 on 2025-07-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_alter_leaveallowance_extra_benefits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endofservicereward',
            name='journal_entry',
        ),
        migrations.AlterField(
            model_name='endofservicereward',
            name='years_of_service',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='عدد سنوات الخدمة'),
        ),
    ]
