# Generated by Django 5.2.3 on 2025-07-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_remove_endofservicereward_last_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='endofservicereward',
            name='days',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='عدد الأيام'),
        ),
        migrations.AddField(
            model_name='endofservicereward',
            name='months',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='عدد الأشهر'),
        ),
        migrations.AddField(
            model_name='endofservicereward',
            name='years',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='عدد السنوات'),
        ),
        migrations.AlterField(
            model_name='endofservicereward',
            name='years_of_service',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='سنوات الخدمة المكافئة'),
        ),
    ]
