# Generated by Django 5.2.3 on 2025-07-25 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_endofservicereward_days_endofservicereward_months_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndOfServicePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رمز السبب (مثلاً resignation)')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم الظاهر')),
                ('first_years', models.PositiveIntegerField(default=5, verbose_name='عدد السنوات الأولى')),
                ('reward_per_year_first', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='أيام لكل سنة - أول سنوات')),
                ('reward_per_year_after', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='أيام لكل سنة - بعد السنوات الأولى')),
                ('percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='نسبة المكافأة (٪)')),
            ],
        ),
        migrations.AlterField(
            model_name='endofservicereward',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.endofservicepolicy', verbose_name='سبب انتهاء الخدمة'),
        ),
    ]
