# Generated by Django 5.2.3 on 2025-07-25 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_alter_endofservicereward_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endofservicepolicy',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='الكود (مثل resignation)'),
        ),
        migrations.AlterField(
            model_name='endofservicepolicy',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم الظاهر (مثلاً استقالة)'),
        ),
        migrations.AlterField(
            model_name='endofservicepolicy',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='النسبة من المكافأة (٪)'),
        ),
        migrations.AlterField(
            model_name='endofservicepolicy',
            name='reward_per_year_after',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='عدد الأيام لكل سنة بعد السنوات الأولى'),
        ),
        migrations.AlterField(
            model_name='endofservicepolicy',
            name='reward_per_year_first',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='عدد الأيام لكل سنة في السنوات الأولى'),
        ),
        migrations.AlterField(
            model_name='endofservicereward',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.endofservicepolicy', verbose_name='سبب انتهاء الخدمة'),
        ),
    ]
