# Generated by Django 5.2.3 on 2025-08-01 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_alter_advance_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollbatch',
            name='month',
            field=models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='الشهر'),
        ),
    ]
