# Generated by Django 5.2.3 on 2026-02-22 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_alter_payrollbatch_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollbatch',
            name='month',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='الشهر'),
        ),
        migrations.AlterField(
            model_name='payrollbatch',
            name='year',
            field=models.PositiveIntegerField(default=2026, verbose_name='السنة'),
        ),
    ]
