# Generated by Django 5.2.3 on 2025-06-24 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=255, verbose_name='اسم التصنيف')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.accountdirection', verbose_name='التصنيف الداخلي'),
        ),
    ]
