# Generated by Django 5.2.3 on 2025-06-24 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountdirection_alter_account_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الرمز')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'نوع القوائم المالية',
                'verbose_name_plural': 'أنواع القوائم المالية',
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='statement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.financialstatementtype', verbose_name='نوع الحساب (القائمة المالية)'),
        ),
    ]
