# Generated by Django 5.2.1 on 2025-07-05 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_financialstatementtype_alter_account_statement_type'),
        ('manufacturing', '0025_alter_productionorder_scrap_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='manufacturing.productionorder', verbose_name='أمر الإنتاج المرتبط'),
        ),
    ]
