# Generated by Django 5.2.3 on 2025-07-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_journalentryline_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroup',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('operating', 'الأنشطة التشغيلية'), ('investing', 'الأنشطة الاستثمارية'), ('financing', 'الأنشطة التمويلية')], max_length=20, null=True, verbose_name='نوع النشاط في التدفقات النقدية'),
        ),
    ]
