# Generated by Django 5.2.2 on 2025-06-19 09:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBalanceDummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'تقرير أرصدة الأصناف',
                'verbose_name_plural': 'تقرير أرصدة الأصناف',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryReportsDummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'تقرير حركة الأصناف',
                'verbose_name_plural': 'تقرير حركة الأصناف',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('raw', 'مواد خام'), ('semi', 'نصف مصنع'), ('finished', 'منتج نهائي')], max_length=10)),
                ('conversion_factor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pricing_method', models.CharField(choices=[('fifo', 'الوارد أولاً يصرف أولاً'), ('average', 'متوسط التكلفة')], default='fifo', max_length=10, verbose_name='طريقة احتساب التكلفة')),
                ('average_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_base', models.BooleanField(default=False)),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('warehouse_type', models.CharField(choices=[('main', 'رئيسي'), ('branch', 'فرعي'), ('external', 'خارجي')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('out', 'أمر صرف'), ('in', 'أمر إضافة')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningStockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_posted', models.BooleanField(default=False, verbose_name='تم الترحيل')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='القيد المحاسبي')),
            ],
            options={
                'verbose_name': 'رصيد أول المدة',
                'verbose_name_plural': 'Opening Stock',
            },
        ),
        migrations.CreateModel(
            name='OpeningStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.openingstockbalance')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('in', 'إدخال'), ('out', 'إخراج'), ('adjust', 'تسوية')], max_length=10)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('is_posted', models.BooleanField(default=False, verbose_name='تم الترحيل؟')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry')),
            ],
        ),
    ]
