# Generated by Django 5.2.1 on 2025-07-05 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_financialstatementtype_alter_account_statement_type'),
        ('inventory', '0008_alter_warehouse_warehouse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='expense_allocation_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_expense_allocation', to='accounts.account', verbose_name='حساب تحميل المصروفات'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='production_cost_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_production_cost', to='accounts.account', verbose_name='حساب تكلفة الإنتاج'),
        ),
    ]
