# Generated by Django 5.2.3 on 2025-07-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReportsFakeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '📦 تقارير المستودعات',
                'verbose_name_plural': '📦 تقارير المستودعات',
                'managed': False,
            },
        ),
    ]
