# Generated by Django 5.2.3 on 2025-07-31 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventoryreportsfakemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openingstockbalance',
            options={'verbose_name': 'رصيد افتتاحي للمخزون', 'verbose_name_plural': 'الأرصدة الافتتاحية للمخزون'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'verbose_name': 'حركة مخزون', 'verbose_name_plural': 'حركات المخزون'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'وحدة', 'verbose_name_plural': 'الوحدات'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'مستودع', 'verbose_name_plural': 'المستودعات'},
        ),
    ]
