# Generated by Django 5.2.3 on 2026-02-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_openingstockbalance_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='openingstockbalance',
            constraint=models.UniqueConstraint(fields=('warehouse', 'date'), name='uniq_opening_balance_warehouse_date'),
        ),
    ]
