# Generated by Django 5.2.1 on 2025-06-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_remove_appliedcosttobom_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterials',
            name='value',
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='total_component_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='total_expense_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
