# Generated by Django 5.2.1 on 2025-06-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_remove_billofmaterials_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcosttobom',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
