# Generated by Django 5.2.1 on 2025-06-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_appliedcosttobom_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcosttobom',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
