# Generated by Django 5.2.3 on 2025-06-27 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0009_remove_appliedcosttobom_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedcosttobom',
            name='account',
        ),
        migrations.AddField(
            model_name='appliedcosttobom',
            name='expense',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='manufacturing.productionexpense', verbose_name='المصروف'),
            preserve_default=False,
        ),
    ]
