# Generated by Django 5.2.3 on 2025-06-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0011_productionordercomponent_productionorderexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
