# Generated by Django 5.2.1 on 2025-07-03 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stocktransactionitem_total_cost'),
        ('manufacturing', '0015_productionorder_is_finished_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'finished'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
