# Generated by Django 5.2.1 on 2025-07-03 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_component'),
        ('manufacturing', '0016_alter_productionorder_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.component')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_bom_components', to='inventory.product')),
            ],
            options={
                'unique_together': {('product', 'component')},
            },
        ),
    ]
