# Generated by Django 5.2.1 on 2025-07-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0018_productionordercomponent_unit_productbomexpense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
