# Generated by Django 5.2.1 on 2025-07-03 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0019_productionorder_is_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
