# Generated by Django 5.2.1 on 2025-07-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0023_remove_productionorder_expense_allocation_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='scrap_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
