# Generated by Django 5.2.1 on 2025-07-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0024_productionorder_scrap_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='scrap_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='التوالف'),
        ),
    ]
