# Generated by Django 5.2.1 on 2025-07-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0025_alter_productionorder_scrap_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='تم الإغلاق'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='is_materials_issued',
            field=models.BooleanField(default=False, verbose_name='تم صرف المواد'),
        ),
    ]
