# Generated by Django 5.2.1 on 2025-07-06 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_product_product_type'),
        ('manufacturing', '0028_remove_productionorder_scrap_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='is_finished_product',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='scrap_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrap_production_order', to='inventory.stocktransaction'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='finished_goods_warehouse',
            field=models.ForeignKey(blank=True, limit_choices_to={'warehouse_type': 'finished'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_orders', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='finished_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='is_materials_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='raw_material_warehouse',
            field=models.ForeignKey(blank=True, limit_choices_to={'warehouse_type': 'raw'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_orders', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='scrap_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='scrap_warehouse',
            field=models.ForeignKey(blank=True, limit_choices_to={'warehouse_type': 'scrap'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scrap_orders', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='wip_warehouse',
            field=models.ForeignKey(blank=True, limit_choices_to={'warehouse_type': 'wip'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wip_orders', to='inventory.warehouse'),
        ),
    ]
