# Generated by Django 5.2.3 on 2025-07-06 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_product_product_type'),
        ('manufacturing', '0029_remove_productionorder_is_finished_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingReportsFakeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '📊 تقارير التصنيع',
                'verbose_name_plural': '📊 تقارير التصنيع',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit_cost', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='manufacturing.productionorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
    ]
