# Generated by Django 5.2.3 on 2025-07-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0031_alter_productionordermaterial_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManufacturingReportDummy',
        ),
    ]
