# Generated by Django 5.2.3 on 2025-07-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0004_remove_treasuryvoucher_responsible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasuryvoucher',
            old_name='responsible_employee',
            new_name='responsible',
        ),
    ]
