# Generated by Django 5.2.3 on 2025-07-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0006_treasurybox_opening_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryReportsFakeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '💰 تقارير الصندوق',
                'verbose_name_plural': '💰 تقارير الصندوق',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='treasurybox',
            options={'verbose_name': 'صندوق', 'verbose_name_plural': 'الصناديق'},
        ),
        migrations.AlterModelOptions(
            name='treasuryvoucher',
            options={'verbose_name': 'سند خزنة', 'verbose_name_plural': 'سندات الخزنة'},
        ),
    ]
