# Generated by Django 5.2.3 on 2025-07-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgingReportFakeModel',
        ),
        migrations.DeleteModel(
            name='CustomerLedgerReportFakeModel',
        ),
        migrations.DeleteModel(
            name='SalesByCustomerReportFakeModel',
        ),
        migrations.DeleteModel(
            name='SalesByProductAndCustomerFakeModel',
        ),
        migrations.AlterModelOptions(
            name='salesreportsfakemodel',
            options={'managed': False, 'verbose_name': '📊 تقارير المبيعات', 'verbose_name_plural': '📊 تقارير المبيعات'},
        ),
    ]
