# Generated by Django 5.2.3 on 2025-07-31 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_delete_agingreportfakemodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'عميل', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.AlterModelOptions(
            name='customergroup',
            options={'verbose_name': 'مجموعة عملاء', 'verbose_name_plural': 'مجموعات العملاء'},
        ),
        migrations.AlterModelOptions(
            name='customerpayment',
            options={'verbose_name': 'دفعة عميل', 'verbose_name_plural': 'دفعات العملاء'},
        ),
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'verbose_name': 'فاتورة مبيعات', 'verbose_name_plural': 'فواتير المبيعات'},
        ),
        migrations.AlterModelOptions(
            name='salesreturn',
            options={'verbose_name': 'مرتجع مبيعات', 'verbose_name_plural': 'مرتجعات المبيعات'},
        ),
    ]
