# Generated by Django 5.2.3 on 2025-08-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_salesrepresentative_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepresentative',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='كود المندوب'),
        ),
    ]
