# Generated by Django 5.2.3 on 2025-08-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salesrepresentative_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي'),
        ),
    ]
